stages:
  prepare:
    cmd: python preprocessing.py
    deps:
      - preprocessing.py
      - data/MELBOURNE_HOUSE_PRICES_LESS.csv
    outs:
      - data/train.csv
      - data/test.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv
    outs:
      - models/model.joblib
  evaluate:
    cmd: python validation.py
    deps:
      - validation.py
      - data/test.csv
      - models/model.joblib
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false